<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UnitJualSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('unit_juals')->insert([
            [
                'unit_id' => 12,
                'harga_jual' => '150000000.00',
                'harga_netto' => '140000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 13,
                'harga_jual' => '155000000.00',
                'harga_netto' => '145000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 14,
                'harga_jual' => '160000000.00',
                'harga_netto' => '150000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 15,
                'harga_jual' => '165000000.00',
                'harga_netto' => '155000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 16,
                'harga_jual' => '170000000.00',
                'harga_netto' => '160000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 17,
                'harga_jual' => '175000000.00',
                'harga_netto' => '165000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 18,
                'harga_jual' => '180000000.00',
                'harga_netto' => '170000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 19,
                'harga_jual' => '185000000.00',
                'harga_netto' => '175000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 20,
                'harga_jual' => '190000000.00',
                'harga_netto' => '180000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 21,
                'harga_jual' => '195000000.00',
                'harga_netto' => '185000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 22,
                'harga_jual' => '200000000.00',
                'harga_netto' => '190000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 23,
                'harga_jual' => '205000000.00',
                'harga_netto' => '195000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 24,
                'harga_jual' => '210000000.00',
                'harga_netto' => '200000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 25,
                'harga_jual' => '215000000.00',
                'harga_netto' => '205000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 26,
                'harga_jual' => '220000000.00',
                'harga_netto' => '210000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 27,
                'harga_jual' => '225000000.00',
                'harga_netto' => '215000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 28,
                'harga_jual' => '230000000.00',
                'harga_netto' => '220000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 29,
                'harga_jual' => '235000000.00',
                'harga_netto' => '225000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 30,
                'harga_jual' => '240000000.00',
                'harga_netto' => '230000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'unit_id' => 31,
                'harga_jual' => '245000000.00',
                'harga_netto' => '235000000.00',
                'keterangan' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
                'foto_depan' => 'unit_jual/foto_depan/01K62PJC4P6QGYDRRJZTC81Q61.webp',
                'foto_belakang' => 'unit_jual/foto_belakang/01K62PJC8ZXDK6B8TM7ACP5V7M.webp',
                'foto_kiri' => 'unit_jual/foto_kiri/01K62PJCGFCX05V8R17JQAKQT9.webp',
                'foto_kanan' => 'unit_jual/foto_kanan/01K62PJCVHYT4CH8J9164WS6YJ.webp',
                'foto_interior' => 'unit_jual/foto_interior/01K62PJD18GG6FYMSKD70H69C4.webp',
                'foto_odometer' => 'unit_jual/foto_odometer/01K62PJDJHMP0CENFGPBPR95T2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ]

        ]);
    }
}
